<%
  std_opts = "-r features/support/ -r features/step_definitions --format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --format rerun --out rerun.txt --strict --tags ~@wip --tags ~@broken"
%>
default: <%= std_opts %> features

