# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3695133d3c1e2379b049a460f813d64de4d66a044a7fb1c3edda4d568bbc6ae2ade6c3a207e8f1cc34a72c22838e385fe80520dedfd80e23f0555eae32fd309b

test:
  secret_key_base: b5f9b2340b36be95564f5dd252954bb0dd1f270b0850a1da1bef2dd67104d5821db9a0d39dd8b9d4cb7cfe585491299ce68aa703f15b862d6fff105ec96df597
  email_provider_username: test
  email_provider_password: test
  domain_name: localhost
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  AWS_ACCESS_KEY_ID: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  AWS_SECRET_ACCESS_KEY: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  AWS_BUCKET: <%= ENV["AWS_BUCKET"] %>
  default_sender: 'test@test.com'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  AWS_ACCESS_KEY_ID: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  AWS_SECRET_ACCESS_KEY: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  AWS_BUCKET: <%= ENV["AWS_BUCKET"] %>
